"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { collection, onSnapshot, query, where } from "firebase/firestore";
import type { CompetitionRecord, CompetitionTeamRecord, InternshipRecord } from "@/lib/models";
import { getFirebase } from "@/lib/firebase";
import { callFunction, readableError } from "@/lib/callable";
import { formatDeadline } from "@/lib/date";
import { useAuth } from "./auth-provider";

type ResponseRecord = { id: string; opportunityId?: string; internshipId?: string; status: string; registeredLate?: boolean; externalRegistration?: { status: "pending" | "confirmed" }; internalForm?: { status: "pending" | "confirmed" } };
type ConfirmationRow = ResponseRecord & { uid: string; studentSnapshot?: { displayName: string; rollNumber: string }; wingId?: string };
type RoundRecord = { id: string; competitionId: string; name: string; status: string };
type RoundEntry = { id: string; roundId: string; teamId: string; submissionStatus: string };
const indiaIso = (value: string) => new Date(`${value}:00+05:30`).toISOString();
const indiaLocalInput = (date: Date) => new Date(date.getTime() + 330 * 60_000).toISOString().slice(0, 16);
const normalizeUrl = (value: string) => /^https?:\/\//i.test(value.trim()) ? value.trim() : `https://${value.trim()}`;

export function OpportunitiesView({ mode = "all" }: { mode?: "all" | "teams" }) {
  const { user, profile } = useAuth(); const governor = Boolean(profile?.roles.systemAdmin || profile?.roles.cr); const manager = Boolean(governor || profile?.scopes.batchPocRoles?.caseCompetition); const teamsOnly = mode === "teams";
  const [competitions, setCompetitions] = useState<CompetitionRecord[]>([]); const [internships, setInternships] = useState<InternshipRecord[]>([]); const [responses, setResponses] = useState<ResponseRecord[]>([]); const [internshipResponses, setInternshipResponses] = useState<ResponseRecord[]>([]); const [teams, setTeams] = useState<CompetitionTeamRecord[]>([]); const [rounds, setRounds] = useState<RoundRecord[]>([]); const [entries, setEntries] = useState<RoundEntry[]>([]);
  const [competition, setCompetition] = useState({ title: "", organizer: "", description: "", externalRegistrationUrl: "", internalFormUrl: "", registrationDeadline: "", minTeamSize: 2, maxTeamSize: 4 }); const [internship, setInternship] = useState({ company: "", role: "", description: "", registrationUrl: "", registrationDeadline: "" }); const [editingCompetitionId, setEditingCompetitionId] = useState(""); const [editingInternshipId, setEditingInternshipId] = useState("");
  const [team, setTeam] = useState({ competitionId: "", name: "", memberRollNumbers: "" }); const [round, setRound] = useState({ competitionId: "", name: "", instructions: "", submissionDeadline: "", eligibleTeamIds: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [confirmationReport, setConfirmationReport] = useState<{ competitionId: string; rows: ConfirmationRow[] } | null>(null);

  useEffect(() => {
    if (!user || !profile) return; const db = getFirebase().db;
    const unsubs = [onSnapshot(manager ? collection(db, "competitions") : query(collection(db, "competitions"), where("status", "in", ["published", "in_progress", "completed"])), (snap) => setCompetitions(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as CompetitionRecord)), (err) => setError(readableError(err))), onSnapshot(governor ? collection(db, "internships") : query(collection(db, "internships"), where("status", "in", ["published", "completed"])), (snap) => setInternships(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as InternshipRecord)), (err) => setError(readableError(err))), onSnapshot(query(collection(db, "opportunityResponses"), where("uid", "==", user.uid)), (snap) => setResponses(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as ResponseRecord))), onSnapshot(query(collection(db, "internshipResponses"), where("uid", "==", user.uid)), (snap) => setInternshipResponses(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as ResponseRecord))), onSnapshot(manager ? collection(db, "competitionTeams") : query(collection(db, "competitionTeams"), where("memberUids", "array-contains", user.uid)), (snap) => setTeams(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as CompetitionTeamRecord))), onSnapshot(query(collection(db, "competitionRounds"), where("status", "in", ["open", "finalized"])), (snap) => setRounds(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as RoundRecord))), onSnapshot(manager ? collection(db, "competitionRoundEntries") : query(collection(db, "competitionRoundEntries"), where("memberUids", "array-contains", user.uid)), (snap) => setEntries(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as RoundEntry)))]; return () => unsubs.forEach((unsubscribe) => unsubscribe());
  }, [user, profile, manager, governor]);

  const responseByCompetition = useMemo(() => new Map(responses.map((item) => [item.opportunityId, item])), [responses]); const responseByInternship = useMemo(() => new Map(internshipResponses.map((item) => [item.internshipId, item])), [internshipResponses]);
  async function run(name: string, payload: unknown, success: string) { setBusy(true); setError(""); setMessage(""); try { await callFunction(name, payload); setMessage(success); } catch (err) { setError(readableError(err)); } finally { setBusy(false); } }
  async function saveCompetition(event: FormEvent) { event.preventDefault(); await run(editingCompetitionId ? "updateCompetition" : "createCompetition", { ...competition, externalRegistrationUrl: normalizeUrl(competition.externalRegistrationUrl), internalFormUrl: normalizeUrl(competition.internalFormUrl), ...(editingCompetitionId ? { competitionId: editingCompetitionId } : {}), registrationDeadlineIso: indiaIso(competition.registrationDeadline) }, editingCompetitionId ? "Competition updated." : "Competition draft created."); setCompetition((current) => ({ ...current, title: "", organizer: "", description: "", externalRegistrationUrl: "", internalFormUrl: "" })); setEditingCompetitionId(""); }
  async function saveInternship(event: FormEvent) { event.preventDefault(); await run(editingInternshipId ? "updateInternship" : "createInternship", { ...internship, registrationUrl: internship.registrationUrl ? normalizeUrl(internship.registrationUrl) : "", ...(editingInternshipId ? { internshipId: editingInternshipId } : {}), registrationDeadlineIso: indiaIso(internship.registrationDeadline) }, editingInternshipId ? "Internship updated." : "Internship draft created."); setEditingInternshipId(""); }
  function editCompetition(item: CompetitionRecord) { setEditingCompetitionId(item.id); setCompetition({ title: item.title, organizer: item.organizer, description: item.description, externalRegistrationUrl: item.externalRegistrationUrl ?? item.registrationUrl ?? "", internalFormUrl: item.internalFormUrl ?? "", registrationDeadline: indiaLocalInput(item.registrationDeadline.toDate()), minTeamSize: item.minTeamSize, maxTeamSize: item.maxTeamSize }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function createTeam(event: FormEvent) { event.preventDefault(); const rolls = team.memberRollNumbers.split(/[\s,;]+/).map((value) => value.trim().toUpperCase()).filter(Boolean); if (profile && !rolls.includes(profile.rollNumber)) rolls.unshift(profile.rollNumber); await run("createTeam", { competitionId: team.competitionId, name: team.name, memberRollNumbers: rolls }, "Team draft created."); setTeam((current) => ({ ...current, name: "", memberRollNumbers: "" })); }
  async function createRound(event: FormEvent) { event.preventDefault(); await run("createNextRound", { competitionId: round.competitionId, name: round.name, instructions: round.instructions, submissionDeadlineIso: indiaIso(round.submissionDeadline), eligibleTeamIds: round.eligibleTeamIds.split(/[\s,;]+/).filter(Boolean) }, "Round opened."); }
  async function loadConfirmationReport(competitionId: string) { setBusy(true); setError(""); try { const data = await callFunction<{ competitionId: string }, { responses: ConfirmationRow[] }>("getCompetitionConfirmationReport", { competitionId }); setConfirmationReport({ competitionId, rows: data.responses }); } catch (err) { setError(readableError(err)); } finally { setBusy(false); } }
  async function correctConfirmation(row: ConfirmationRow, kind: "externalRegistration" | "internalForm") { if (!confirmationReport) return; const reason = window.prompt("Reason for this audited correction"); if (!reason) return; const current = row[kind]?.status ?? "pending"; await run("correctCompetitionConfirmation", { competitionId: confirmationReport.competitionId, uid: row.uid, kind, status: current === "confirmed" ? "pending" : "confirmed", reason }, "Confirmation corrected."); await loadConfirmationReport(confirmationReport.competitionId); }

  return <div className="page-wrap"><header className="page-heading"><div><p className="eyebrow">OPPORTUNITIES</p><h1>Competitions, internships, and teams</h1><p>Complete both competition confirmations before your captain registers the team.</p></div></header>{message && <div className="success-banner">{message}</div>}{error && <p className="form-error">{error}</p>}
    {manager && !teamsOnly && <div className="admin-grid"><form className="panel create-form" onSubmit={saveCompetition}><div className="panel-head"><div><p className="eyebrow">CASE COMPETITION</p><h2>{editingCompetitionId ? "Edit competition" : "Create competition"}</h2></div></div><label>Edit existing<select value={editingCompetitionId} onChange={(event) => { const item = competitions.find((candidate) => candidate.id === event.target.value); if (item) editCompetition(item); else setEditingCompetitionId(""); }}><option value="">Create new</option>{competitions.filter((item) => ["draft", "published"].includes(item.status)).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Title<input value={competition.title} onChange={(event) => setCompetition({ ...competition, title: event.target.value })} required /></label><label>Organizer<input value={competition.organizer} onChange={(event) => setCompetition({ ...competition, organizer: event.target.value })} required /></label><label>Details<textarea value={competition.description} onChange={(event) => setCompetition({ ...competition, description: event.target.value })} required /></label><div className="form-row"><label>Min team size<input type="number" min="1" value={competition.minTeamSize} onChange={(event) => setCompetition({ ...competition, minTeamSize: Number(event.target.value) })} /></label><label>Max team size<input type="number" min="1" value={competition.maxTeamSize} onChange={(event) => setCompetition({ ...competition, maxTeamSize: Number(event.target.value) })} /></label></div><label>Deadline · IST<input type="datetime-local" value={competition.registrationDeadline} onChange={(event) => setCompetition({ ...competition, registrationDeadline: event.target.value })} required /></label><label>External registration link<input type="text" inputMode="url" placeholder="forms.google.com/..." value={competition.externalRegistrationUrl} onChange={(event) => setCompetition({ ...competition, externalRegistrationUrl: event.target.value })} required /></label><label>Internal Google Form link<input type="text" inputMode="url" placeholder="forms.google.com/..." value={competition.internalFormUrl} onChange={(event) => setCompetition({ ...competition, internalFormUrl: event.target.value })} required /></label><small>You can paste forms.google.com without https://.</small><button className="primary-button" disabled={busy}>{editingCompetitionId ? "Save changes" : "Create draft"}</button></form>
      {governor && <form className="panel create-form" onSubmit={saveInternship}><div className="panel-head"><div><p className="eyebrow">INTERNSHIP</p><h2>Create internship</h2></div></div><label>Company<input value={internship.company} onChange={(event) => setInternship({ ...internship, company: event.target.value })} required /></label><label>Role<input value={internship.role} onChange={(event) => setInternship({ ...internship, role: event.target.value })} required /></label><label>Details<textarea value={internship.description} onChange={(event) => setInternship({ ...internship, description: event.target.value })} required /></label><label>Deadline · IST<input type="datetime-local" value={internship.registrationDeadline} onChange={(event) => setInternship({ ...internship, registrationDeadline: event.target.value })} required /></label><label>Registration link<input value={internship.registrationUrl} onChange={(event) => setInternship({ ...internship, registrationUrl: event.target.value })} /></label><button className="primary-button" disabled={busy}>Create draft</button></form>}
    </div>}
    {manager && !teamsOnly && <section className="panel report-teams"><div className="panel-head"><div><p className="eyebrow">PRIVATE COMPLIANCE</p><h2>Competition form confirmations</h2></div><select aria-label="Choose competition report" value={confirmationReport?.competitionId ?? ""} onChange={(event) => { if (event.target.value) void loadConfirmationReport(event.target.value); }}><option value="">Choose competition</option>{competitions.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div>{confirmationReport ? <div className="simple-table">{confirmationReport.rows.map((row) => <div className="simple-table-row" key={row.id}><strong>{row.studentSnapshot?.displayName ?? row.uid}</strong><span>{row.studentSnapshot?.rollNumber ?? ""}</span><span>Wing {row.wingId ?? "–"}</span><span>External: {row.externalRegistration?.status ?? "pending"} <button className="text-button" onClick={() => void correctConfirmation(row, "externalRegistration")}>Correct</button><br />Internal: {row.internalForm?.status ?? "pending"} <button className="text-button" onClick={() => void correctConfirmation(row, "internalForm")}>Correct</button></span></div>)}</div> : <p className="helper">Choose a competition to inspect named confirmation status.</p>}</section>}
    {!teamsOnly && <div className="opportunity-grid"><section className="panel managed-list"><div className="panel-head"><div><p className="eyebrow">CASE COMPETITIONS</p><h2>Registration tracker</h2></div><span className="count-badge">{competitions.length}</span></div>{competitions.map((item) => { const response = responseByCompetition.get(item.id); const canConfirm = response?.status === "team_draft"; return <article className="opportunity-card" key={item.id}><div><span className={`status-pill ${item.status}`}>{item.status}</span><h3>{item.title}</h3><p>{item.organizer} · {formatDeadline(item.registrationDeadline)}</p><small>Team size {item.minTeamSize}–{item.maxTeamSize}</small></div><div className="opportunity-actions">{item.externalRegistrationUrl && <a className="resource-link" href={item.externalRegistrationUrl} target="_blank" rel="noreferrer">External form</a>}{item.internalFormUrl && <a className="resource-link" href={item.internalFormUrl} target="_blank" rel="noreferrer">Internal form</a>}{canConfirm && <><button className={response.externalRegistration?.status === "confirmed" ? "primary-button" : "secondary-button"} onClick={() => run(response.externalRegistration?.status === "confirmed" ? "reopenCompetitionConfirmation" : "setCompetitionConfirmation", { competitionId: item.id, kind: "externalRegistration" }, "External confirmation updated.")} disabled={busy}>{response.externalRegistration?.status === "confirmed" ? "External ✓" : "Confirm external"}</button><button className={response.internalForm?.status === "confirmed" ? "primary-button" : "secondary-button"} onClick={() => run(response.internalForm?.status === "confirmed" ? "reopenCompetitionConfirmation" : "setCompetitionConfirmation", { competitionId: item.id, kind: "internalForm" }, "Internal confirmation updated.")} disabled={busy}>{response.internalForm?.status === "confirmed" ? "Internal ✓" : "Confirm internal"}</button></>}{item.status === "published" && response?.status === "no_response" && <button className="secondary-button" onClick={() => run("setCompetitionResponse", { opportunityId: item.id, status: "not_participating" }, "Response recorded.")} disabled={busy}>Not participating</button>}{manager && item.status === "draft" && <button onClick={() => run("publishCompetition", { competitionId: item.id }, "Competition published.")} disabled={busy}>Publish</button>}{manager && ["draft", "published"].includes(item.status) && <button className="danger-link text-button" onClick={() => { const reason = window.prompt("Cancellation reason"); if (reason) void run("cancelCompetition", { competitionId: item.id, reason }, "Competition cancelled."); }}>Cancel</button>}<small>My status: {response?.status?.replaceAll("_", " ") ?? "manager"}</small></div></article>; })}</section>
      <section className="panel managed-list"><div className="panel-head"><div><p className="eyebrow">INTERNSHIPS</p><h2>Registration tracker</h2></div><span className="count-badge">{internships.length}</span></div>{internships.map((item) => { const response = responseByInternship.get(item.id); return <article className="opportunity-card" key={item.id}><div><span className={`status-pill ${item.status}`}>{item.status}</span><h3>{item.company} · {item.role}</h3><p>{formatDeadline(item.registrationDeadline)}</p></div><div className="opportunity-actions">{item.registrationUrl && <a className="resource-link" href={item.registrationUrl} target="_blank" rel="noreferrer">Open form</a>}{item.status === "published" && <><button onClick={() => run("setInternshipResponse", { internshipId: item.id, status: "registered", confirmationReference: "self-attested" }, "Registration recorded.")}>I registered</button><button className="secondary-button" onClick={() => run("setInternshipResponse", { internshipId: item.id, status: "not_participating" }, "Response recorded.")}>Not participating</button></>}{governor && item.status === "draft" && <button onClick={() => run("publishInternship", { internshipId: item.id }, "Internship published.")}>Publish</button>}<small>My status: {response?.status ?? "manager"}</small></div></article>; })}</section></div>}
    <div className="two-column opportunities-lower"><form className="panel create-form" onSubmit={createTeam}><div className="panel-head"><div><p className="eyebrow">MY TEAMS</p><h2>Create team</h2></div></div><label>Competition<select value={team.competitionId} onChange={(event) => setTeam({ ...team, competitionId: event.target.value })}><option value="">Choose competition</option>{competitions.filter((item) => item.status === "published").map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Team name<input value={team.name} onChange={(event) => setTeam({ ...team, name: event.target.value })} required /></label><label>Member roll numbers<textarea value={team.memberRollNumbers} onChange={(event) => setTeam({ ...team, memberRollNumbers: event.target.value })} placeholder="24M2002, 24M2003" /></label><button className="primary-button" disabled={busy || !team.competitionId}>Create team</button></form><section className="panel managed-list"><div className="panel-head"><div><p className="eyebrow">TEAMS</p><h2>{manager ? "Batch teams" : "My teams"}</h2></div><span className="count-badge">{teams.length}</span></div>{teams.map((item) => <article className="managed-task" key={item.id}><div><span className={`status-pill ${item.status}`}>{item.status}</span><h3>{item.name}</h3><p>{item.members.map((member) => member.rollNumber).join(", ")}</p></div><div className="managed-actions">{item.captainUid === user?.uid && item.status === "draft" && <><button onClick={() => run("registerTeam", { teamId: item.id }, "Team registered.")} disabled={busy}>Register team</button><button className="danger-link" onClick={() => run("deleteDraftTeam", { teamId: item.id }, "Draft deleted.")}>Delete</button></>}{entries.filter((entry) => entry.teamId === item.id && entry.submissionStatus === "pending").map((entry) => { const activeRound = rounds.find((candidate) => candidate.id === entry.roundId); return item.captainUid === user?.uid && activeRound ? <button key={entry.id} onClick={() => run("markRoundSubmitted", { roundId: entry.roundId, teamId: item.id, confirmationReference: "self-attested" }, "Submission recorded.")}>Submit {activeRound.name}</button> : null; })}</div></article>)}</section></div>
    {manager && <form className="panel create-form" onSubmit={createRound}><div className="panel-head"><div><p className="eyebrow">ROUNDS</p><h2>Open next round</h2></div></div><div className="form-row"><label>Competition<select value={round.competitionId} onChange={(event) => setRound({ ...round, competitionId: event.target.value })}><option value="">Choose</option>{competitions.filter((item) => ["published", "in_progress"].includes(item.status)).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Round name<input value={round.name} onChange={(event) => setRound({ ...round, name: event.target.value })} /></label></div><label>Instructions<textarea value={round.instructions} onChange={(event) => setRound({ ...round, instructions: event.target.value })} /></label><div className="form-row"><label>Deadline · IST<input type="datetime-local" value={round.submissionDeadline} onChange={(event) => setRound({ ...round, submissionDeadline: event.target.value })} /></label><label>Eligible team IDs<input value={round.eligibleTeamIds} onChange={(event) => setRound({ ...round, eligibleTeamIds: event.target.value })} /></label></div><button className="primary-button" disabled={busy}>Open round</button></form>}
  </div>;
}
