"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { collection, onSnapshot, query, where } from "firebase/firestore";
import { getFirebase } from "@/lib/firebase";
import { callFunction, readableError } from "@/lib/callable";
import { formatDeadline } from "@/lib/date";
import type { GeneralPollRecord, PollResponseRecord, SessionIntimationRecord } from "@/lib/models";
import { useAuth } from "./auth-provider";

function indiaIso(value: string) { return new Date(`${value}:00+05:30`).toISOString(); }
function localInput(date: Date) { return new Date(date.getTime() + 330 * 60_000).toISOString().slice(0, 16); }

export function PollsView() {
  const { user, profile } = useAuth();
  const manager = Boolean(profile?.roles.cr || profile?.roles.systemAdmin || profile?.scopes.batchPocRoles?.grooming);
  const [polls, setPolls] = useState<GeneralPollRecord[]>([]); const [responses, setResponses] = useState<PollResponseRecord[]>([]);
  const [sessions, setSessions] = useState<SessionIntimationRecord[]>([]);
  const [form, setForm] = useState({ question: "", details: "", options: "Yes\nNo", closesAt: "", linkedSessionId: "" });
  const [editingPollId, setEditingPollId] = useState("");
  const [report, setReport] = useState<{ pollId: string; rows: PollResponseRecord[]; stats?: { optionCounts?: Record<string, number> } } | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { if (!user || !profile) return; const db = getFirebase().db; const pollsQuery = manager ? collection(db, "generalPolls") : query(collection(db, "generalPolls"), where("status", "in", ["published", "closed", "cancelled"])); const unsubPolls = onSnapshot(pollsQuery, (snap) => setPolls(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as GeneralPollRecord)), (err) => setError(readableError(err))); const unsubResponses = onSnapshot(query(collection(db, "pollResponses"), where("uid", "==", user.uid)), (snap) => setResponses(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as PollResponseRecord)), (err) => setError(readableError(err))); const unsubSessions = onSnapshot(query(collection(db, "sessionIntimations"), where("status", "==", "published")), (snap) => setSessions(snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as SessionIntimationRecord))); return () => { unsubPolls(); unsubResponses(); unsubSessions(); }; }, [user, profile, manager]);
  const responseByPoll = useMemo(() => new Map(responses.map((item) => [item.pollId, item])), [responses]);
  async function run(name: string, payload: unknown, success: string) { setBusy(true); setError(""); setMessage(""); try { await callFunction(name, payload); setMessage(success); } catch (err) { setError(readableError(err)); } finally { setBusy(false); } }
  async function create(event: FormEvent) { event.preventDefault(); const options = form.options.split("\n").map((label) => label.trim()).filter(Boolean).map((label, index) => ({ id: `option_${index + 1}`, label })); await run(editingPollId ? "updateGeneralPoll" : "createGeneralPoll", { ...(editingPollId ? { pollId: editingPollId } : {}), question: form.question, details: form.details, options, closesAtIso: indiaIso(form.closesAt), linkedSessionId: form.linkedSessionId }, editingPollId ? "Poll updated." : "Poll draft created."); setForm({ question: "", details: "", options: "Yes\nNo", closesAt: "", linkedSessionId: "" }); setEditingPollId(""); }
  function edit(poll: GeneralPollRecord) { setEditingPollId(poll.id); setForm({ question: poll.question, details: poll.details ?? "", options: poll.options.map((option) => option.label).join("\n"), closesAt: localInput(poll.closesAt.toDate()), linkedSessionId: poll.linkedSessionId ?? "" }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function loadReport(pollId: string) { setBusy(true); try { const data = await callFunction<{ pollId: string }, { responses: PollResponseRecord[]; stats?: { optionCounts?: Record<string, number> } }>("getPollReport", { pollId }); setReport({ pollId, rows: data.responses, stats: data.stats }); } catch (err) { setError(readableError(err)); } finally { setBusy(false); } }
  return <div className="page-wrap"><header className="page-heading"><div><p className="eyebrow">GENERAL AREA</p><h1>Batch polls</h1><p>Respond to non-academic, non-placement questions. Results are visible only to authorized managers.</p></div></header>{message && <div className="success-banner">{message}</div>}{error && <p className="form-error">{error}</p>}
    {manager && <form className="panel create-form" onSubmit={create}><div className="panel-head"><div><p className="eyebrow">CREATE POLL</p><h2>{editingPollId ? "Edit draft poll" : "Ask the batch"}</h2></div></div><label>Question<input value={form.question} onChange={(event) => setForm({ ...form, question: event.target.value })} required /></label><label>Optional details<textarea value={form.details} onChange={(event) => setForm({ ...form, details: event.target.value })} /></label><label>Options · one per line<textarea value={form.options} onChange={(event) => setForm({ ...form, options: event.target.value })} rows={4} required /></label><label>Optional related session<select value={form.linkedSessionId} onChange={(event) => setForm({ ...form, linkedSessionId: event.target.value })}><option value="">No linked session</option>{sessions.map((session) => <option key={session.id} value={session.id}>{session.title}</option>)}</select></label><label>Closes at · IST<input type="datetime-local" value={form.closesAt} onChange={(event) => setForm({ ...form, closesAt: event.target.value })} required /></label><div className="form-actions">{editingPollId && <button type="button" className="secondary-button" onClick={() => setEditingPollId("")}>Cancel edit</button>}<button className="primary-button" disabled={busy}>{editingPollId ? "Save changes" : "Create draft"}</button></div></form>}
    <section className="panel managed-list"><div className="panel-head"><div><p className="eyebrow">POLLS</p><h2>Open and previous</h2></div><span className="count-badge">{polls.length}</span></div>{!polls.length && <p className="helper">No polls are available.</p>}{[...polls].sort((a, b) => b.closesAt.toMillis() - a.closesAt.toMillis()).map((poll) => { const response = responseByPoll.get(poll.id); const open = poll.status === "published" && poll.closesAt.toMillis() > Date.now(); return <article className="managed-task" key={poll.id}><div><span className={`status-pill ${poll.status}`}>{poll.status}</span><h3>{poll.question}</h3>{poll.details && <p>{poll.details}</p>}<small>Closes {formatDeadline(poll.closesAt)} · Your answer: {poll.options.find((option) => option.id === response?.optionId)?.label ?? "not answered"}</small></div><div className="managed-actions">{open && response && poll.options.map((option) => <button key={option.id} className={response.optionId === option.id ? "primary-button" : "secondary-button"} onClick={() => run("setPollResponse", { pollId: poll.id, optionId: option.id }, "Poll response saved.")} disabled={busy}>{option.label}</button>)}{manager && poll.status === "draft" && <><button className="secondary-button" onClick={() => edit(poll)}>Edit</button><button onClick={() => run("publishGeneralPoll", { pollId: poll.id }, "Poll published.")} disabled={busy}>Publish</button></>}{manager && poll.status === "published" && <><button className="secondary-button" onClick={() => void loadReport(poll.id)} disabled={busy}>Named results</button><button onClick={() => run("closeGeneralPoll", { pollId: poll.id }, "Poll closed.")} disabled={busy}>Close</button></>}{manager && ["draft", "published"].includes(poll.status) && <button className="danger-link" onClick={() => { const reason = window.prompt("Cancellation reason"); if (reason) void run("cancelGeneralPoll", { pollId: poll.id, reason }, "Poll cancelled."); }}>Cancel</button>}</div></article>; })}</section>
    {manager && report && <section className="panel"><div className="panel-head"><div><p className="eyebrow">PRIVATE RESULTS</p><h2>Named responses</h2></div><span className="count-badge">{report.rows.filter((row) => row.status === "responded").length}</span></div>{(() => { const poll = polls.find((item) => item.id === report.pollId); const total = Math.max(1, report.rows.filter((row) => row.status === "responded").length); return <div className="stats-grid stats-three">{poll?.options.map((option) => { const count = report.stats?.optionCounts?.[option.id] ?? 0; return <article className="stat-card" key={option.id}><span>{option.label}</span><strong>{count}</strong><small>{Math.round(count / total * 100)}%</small></article>; })}</div>; })()}<div className="simple-table">{report.rows.map((row) => { const poll = polls.find((item) => item.id === report.pollId); return <div className="simple-table-row" key={row.id}><strong>{row.studentSnapshot.displayName}</strong><span>{row.studentSnapshot.rollNumber}</span><span>Wing {row.studentSnapshot.wingId}</span><span>{poll?.options.find((option) => option.id === row.optionId)?.label ?? "No response"}</span></div>; })}</div></section>}
  </div>;
}
